// frontend/React/src/pages/Products.jsx
import { useEffect, useState } from "react";
import API from "../services/api";
import ConfirmModal from "../components/ConfirmModal";
import Alert from "../components/Alert";
function Products() {
  const [products, setProducts] = useState([]);

  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(5);

  const [editingId, setEditingId] = useState(null);
  const [selectedId, setSelectedId] = useState(null);

  const [showModal, setShowModal] = useState(false);

  const [alert, setAlert] = useState({ message: "", type: "primary" });


  const [form, setForm] = useState({
    name: "",
    description: "",
    price: 0,
    category: "Electronics",
    status: "Active",
    tags: []
  });

  useEffect(() => {
    loadProducts();
  }, [page, limit]);

  const loadProducts = async () => {
    const res = await API.get(`/products?page=${page}&limit=${limit}`);
    setProducts(res.data.data);
    setTotal(res.data.total);
  };

  const handleChange = (e) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const toggleTag = (tag) => {
    let updatedTags = [...form.tags];

    if (updatedTags.includes(tag)) {
      updatedTags = updatedTags.filter(t => t !== tag);
    } else {
      updatedTags.push(tag);
    }

    setForm({ ...form, tags: updatedTags });
  };

  const resetForm = () => {
    setEditingId(null);
    setForm({
      name: "",
      description: "",
      price: 0,
      category: "Electronics",
      status: "Active",
      tags: []
    });
  };


  const save = async (e) => {
    e.preventDefault();

    try {
      if (editingId) {
        await API.put(`/products/${editingId}`, form);
        setAlert({ message: "Product updated successfully!", type: "success" });
        setEditingId(null);
      } else {
        await API.post("/products", form);
        setAlert({ message: "Product created successfully!", type: "success" });
      }

      resetForm();
      loadProducts();

    } catch (err) {
      console.log('error', err);
      const errorMessage =
        err.response?.data?.message || "Something went wrong";
      setAlert({ message: errorMessage, type: "danger" });
    }

    setTimeout(() => {
      setAlert({ message: "", type: "primary" });
    }, 3000);
  };

  const edit = (product) => {
    setEditingId(product._id);
    setForm(product);
  };

  const deleteProduct = (id) => {
    setSelectedId(id);
    setShowModal(true);
  };

  const confirmDelete = async () => {
    await API.delete(`/products/${selectedId}`);
    setAlert({ message: "Product deleted successfully!", type: "success" });
    setShowModal(false);
    resetForm();
    loadProducts();
    setTimeout(() => {
      setAlert({ message: "", type: "primary" });
    }, 3000);
  };

  return (
    <div className="container mt-5">
      <h3>Products</h3>

      <div className="card p-4 mb-4">
        <h4>{editingId ? "Edit Product" : "Add Product"}</h4>

        <form>

          <input
            name="name"
            className="form-control mb-2"
            placeholder="Name"
            value={form.name}
            onChange={handleChange}
          />

          <textarea
            name="description"
            className="form-control mb-2"
            placeholder="Description"
            value={form.description}
            onChange={handleChange}
          />

          <input
            type="number"
            name="price"
            className="form-control mb-2"
            value={form.price}
            onChange={handleChange}
          />

          <select
            name="category"
            className="form-select mb-2"
            value={form.category}
            onChange={handleChange}
          >
            <option>Electronics</option>
            <option>Clothing</option>
            <option>Books</option>
          </select>

          <div className="mb-2">
            <input
              type="radio"
              checked={form.status === "Active"}
              onChange={() => setForm({ ...form, status: "Active" })}
            /> Active

            <input
              type="radio"
              className="ms-3"
              checked={form.status === "Inactive"}
              onChange={() => setForm({ ...form, status: "Inactive" })}
            /> Inactive
          </div>

          <div className="mb-2">
            {["New", "Featured", "Sale"].map(tag => (
              <label key={tag} className="me-3">
                <input
                  type="checkbox"
                  checked={form.tags.includes(tag)}
                  onChange={() => toggleTag(tag)}
                /> {tag}
              </label>
            ))}
          </div>

          <button className="btn btn-primary" onClick={save}>
            {editingId ? "Update" : "Save"}
          </button>
          <button type="button" className="btn btn-secondary ms-2" onClick={resetForm}>Clear</button>
        </form>

        <Alert message={alert.message} type={alert.type} />
      </div>

      <div className="card p-3">

        <p>Total products: {total}</p>

        <table className="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Price</th>
              <th>Status</th>
              <th>Category</th>
              <th>Tags</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            {products.map(p => (
              <tr key={p._id}>
                <td>{p.name}</td>
                <td>{p.price}</td>
                <td>{p.status}</td>
                <td>{p.category}</td>
                <td>
                  {p.tags?.map(tag => (
                    <span key={tag} className="badge bg-secondary me-1">
                      {tag}
                    </span>
                  ))}
                </td>
                <td>
                  <button
                    className="btn btn-sm btn-warning me-2"
                    onClick={() => edit(p)}
                  >
                    Edit
                  </button>

                  <button
                    className="btn btn-sm btn-danger"
                    onClick={() => deleteProduct(p._id)}
                  >
                    Delete
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Pagination */}
        <div className="d-flex justify-content-between">

          <div>
            <select
              value={limit}
              onChange={(e) => setLimit(Number(e.target.value))}
              className="form-select w-auto"
            >
              <option value={5}>5</option>
              <option value={10}>10</option>
              <option value={20}>20</option>
            </select>
          </div>

          <div>
            <button
              disabled={page === 1}
              onClick={() => setPage(page - 1)}
              className="btn btn-secondary btn-sm me-2"
            >
              Prev
            </button>

            Page {page}

            <button
              disabled={page * limit >= total}
              onClick={() => setPage(page + 1)}
              className="btn btn-secondary btn-sm ms-2"
            >
              Next
            </button>
          </div>

        </div>
      </div>

      <ConfirmModal
        show={showModal}
        title="Confirm Delete"
        onConfirm={confirmDelete}
        onClose={() => setShowModal(false)}
      >
        Are you sure you want to delete this product?
      </ConfirmModal>

    </div >
  );
}

export default Products;

// frontend/Angular/src/app/pages/products/products.ts
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { ChangeDetectorRef, Component, inject, OnInit, PLATFORM_ID, signal } from '@angular/core';
import { FormBuilder, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { Product } from '../../services/product';
import { Modal } from '../../shared/modal/modal/modal';
import { Alert } from '../../shared/alert/alert/alert';

@Component({
  selector: 'app-products',
  imports: [CommonModule, ReactiveFormsModule, FormsModule, Modal, Alert],
  templateUrl: './products.html',
  styleUrl: './products.css',
})
export class Products implements OnInit {
  private fb = inject(FormBuilder);
  private productService = inject(Product);
  private platformId = inject(PLATFORM_ID);
  private cd = inject(ChangeDetectorRef);

  showDeleteModal = false;
  products: any[] = [];
  total = 0;
  page = 1;
  limit = 5;

  editingId: string | null = null;
  selectedId: string | null = null;

  form = this.fb.nonNullable.group({
    name: ['', Validators.required],
    description: ['', Validators.required],
    price: [0, Validators.required],
    category: ['Electronics'],
    status: ['Active'],
    tags: [[] as string[], Validators.required],
  });

  alertMessage = signal('');
  alertType = signal<'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info'>('primary');

  ngOnInit() {
    if (isPlatformBrowser(this.platformId)) {
      this.loadProducts();
    }
  }

  loadProducts() {
    this.productService.getProducts(this.page, this.limit)
      .subscribe(res => {
        this.products = res.data;
        this.total = res.total;
        console.log('Loaded products:', this.products);
        this.cd.detectChanges();
      });
  }

  save() {
    if (this.form.invalid) return;

    if (this.editingId) {
      this.productService.updateProduct(this.editingId, this.form.value)
        .subscribe(() => {
          this.editingId = null;
          this.form.reset({ status: 'Active', category: 'Electronics', tags: [] });
          this.alertType.set('success');
          this.alertMessage.set('Product updated successfully!');
          setTimeout(() => {
            this.alertMessage.set('');
            this.loadProducts();
          }, 3000);
        });
    } else {
      this.productService.createProduct(this.form.value)
        .subscribe((res: any) => {
          if (res.message === 'Product saved successfully') {
            this.alertType.set('success');
            this.alertMessage.set('Product created successfully!');
            this.form.reset({ status: 'Active', category: 'Electronics', tags: [] });
            setTimeout(() => {
              this.alertMessage.set('');
              this.loadProducts();
            }, 3000);
          }
          else {
            this.alertType.set('danger');
            this.alertMessage.set('Failed to create product.');
          }
        }, error => {
          console.error('Error creating product:', error);
          this.alertType.set('danger');
          this.alertMessage.set('An error occurred while creating the product.');
        });
    }
  }

  edit(product: any) {
    this.editingId = product._id;
    console.log('Editing product:', product);
    this.form.patchValue(product);
  }

  delete(id: string) {
    // if (!confirm('Delete this product?')) return;

    // this.productService.deleteProduct(id)
    //   .subscribe(() => this.loadProducts());

    this.selectedId = id;
    this.showDeleteModal = true;

  }

  deleteConfirmed() {
    if (!this.selectedId) return;

    this.productService.deleteProduct(this.selectedId)
      .subscribe((res: any) => {
        console.log('Delete response:', res);
        if (res.message === 'Deleted successfully') {
          this.alertType.set('success');
          this.alertMessage.set('Product deleted successfully!');
          setTimeout(() => {
            this.alertMessage.set('');
            this.loadProducts();
            this.showDeleteModal = false;
          }, 3000);

        } else {
          this.alertType.set('danger');
          this.alertMessage.set('Failed to delete product.');
        }
      });
  }

  changePage(p: number) {
    this.page = p;
    this.loadProducts();
  }

  toggleTag(tag: string, event: any) {
    console.log('Toggling tag:', tag, event.target.checked);
    let currentTags = this.form.value.tags || [];

    if (event.target.checked) {
      currentTags.push(tag);
    } else {
      const index = currentTags.indexOf(tag);
      if (index > -1) currentTags.splice(index, 1);
    }
    console.log('Current tags after toggle:', currentTags);
    this.form.patchValue({ tags: currentTags });
  }
}
